name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "React-project/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend to GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo "ðŸŸ¦ Updating backend on server..."
            cd /home/${{ secrets.GCP_USER }}/Dashboard
            git pull
            docker compose build backend
            docker compose up -d backend
            echo "âœ… Backend deployed successfully!"